# Generated by Django 4.2.8 on 2023-12-13 12:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Employee Email')),
                ('address', models.TextField(max_length=500, verbose_name='Employee Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Employee Phone')),
                ('doj', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Date of Joining')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Employee salary')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
            ],
        ),
    ]
