# Generated by Django 4.2.8 on 2023-12-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee_gender_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Gender', [('Male', 'Male'), ('Female', 'Female')]), ('unknown', 'Unknown')], default='Male', max_length=10, verbose_name='Gender'),
        ),
    ]
